on: [push]
jobs:
  build_and_static_analysis:
    runs-on: ubuntu-latest
    container:
      image: stronglytyped/arm-none-eabi-gcc:latest
    steps:
      - run: ls -a
      - run: arm-none-eabi-gcc --version
          # sudo apt-get install gcc-arm-none-eabi
          
      - run: arm-none-eabi-gcc main.c startup_stm32f401ccux.c -T STM32F401CCUX_FLASH.ld -o blink.elf -mcpu=cortex-m4 -mthumb -nostdlib
      - run: ls -a
      # - run: git config --local user.email "action@github.com"
      # - run: git config --local user.name "github-actions"
      # - run: git add --all
      # - run: git commit -m "Add changes"
      # - name: Commit files
      #   id: commit
      #   run: |
      #     git config --local user.email "action@github.com"
      #     git config --local user.name "github-actions"
      # - run: |
      #     git add --all
      #     git commit -m "Add changes"
      #   shell: bash
      # - name: Push changes
      #   if: steps.commit.outputs.push == 'true'
      #   uses: ad-m/github-push-action@master
      #   with:
      #      github_token: ${{ secrets.GITHUB_TOKEN }}


