on: [push]
jobs:
  build_and_static_analysis:
    runs-on: ubuntu-latest
    env:
      TOOLS_PATH: /home/ubuntu/dev/tools
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          submodules: "true"
      - run: ls -a
      - run: sudo apt install build-essential
      - run: gcc --version
      - run: gcc main.c -o a.out
      - run: ./a.out
      - run: ls -a
      - run: git commit -am "Add changes"
      - name: Push changes
        if: steps.commit.outputs.push == 'true'
        uses: ad-m/github-push-action@master
