on: [push]
jobs:
  build_and_static_analysis:
    runs-on: ubuntu-latest
    env:
      TOOLS_PATH: /home/ubuntu/dev/tools
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          submodules: "true"
      - run: ls -a
      - run: sudo apt install build-essential
      - run: gcc --version
      - run: |
          sudo apt-get install gcc-arm-none-eabi
          arm-none-eabi-gcc --version
      - run: gcc main.c -o amin.out
      - run: ./amin.out
      - run: ls -a
      # - run: git config --local user.email "action@github.com"
      # - run: git config --local user.name "github-actions"
      # - run: git add --all
      # - run: git commit -m "Add changes"
      # - name: Commit files
      #   id: commit
      #   run: |
      #     git config --local user.email "action@github.com"
      #     git config --local user.name "github-actions"
      # - run: |
      #     git add --all
      #     git commit -m "Add changes"
      #   shell: bash
      # - name: Push changes
      #   if: steps.commit.outputs.push == 'true'
      #   uses: ad-m/github-push-action@master
      #   with:
      #      github_token: ${{ secrets.GITHUB_TOKEN }}


